if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi

alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias cd..='cd ..'
alias cd...='cd .. && cd ..'

alias be='bundle exec'

alias ju='j'
alias xo='xdg-open'
